// Generated by bun-php. Do not edit.
// Source: hello.php

type PhpValue =
  | string
  | number
  | boolean
  | null
  | PhpValue[]
  | { [key: string]: PhpValue };
type PhpArray = PhpValue[] | { [key: string]: PhpValue };

/**
 * Greets someone by name.
 */
export declare function greet(name: string, greeting?: string): Promise<string>;

/**
 * Sums any number of integers.
 */
export declare function addAll(...numbers: number[]): Promise<number>;

/**
 * Summarises a list of numbers.
 */
export declare function stats(values: number[]): Promise<Record<string, number>>;

/**
 * Formats a number the way PHP's intl-free number_format does.
 */
export declare function money(amount: number, decimals?: number): Promise<string>;

export declare const GREETING: "Hello";

declare const _default: {
  /** Call a PHP function by its fully-qualified name. */
  call(name: string, args: readonly unknown[]): Promise<any>;
  /** Boot the interpreter without calling anything. */
  $ready(): Promise<void>;
  /** Discard all PHP state; the next call boots a fresh interpreter. */
  $reset(): Promise<void>;
  /** Shut the interpreter down and drop it from the cache. */
  $dispose(): Promise<void>;
  /** Evaluate PHP with this file already required. `onOutput` takes the output away from the stdout mode. */
  $eval(code: string, onOutput?: (text: string) => void): Promise<any>;
  /** The underlying php-wasm instance. */
  $php(): Promise<any>;
  /** Drain output collected under `stdout: "capture"`. */
  $output(): string;
  /** What the parser found in this file. */
  $meta: {
    functions: readonly unknown[];
    constants: readonly unknown[];
    skipped: readonly string[];
  };
  greet: typeof greet;
  addAll: typeof addAll;
  stats: typeof stats;
  money: typeof money;
};
export default _default;
