import type { PhpModuleMeta, StdoutMode } from "./types";

/**
 * Words that cannot be used as a `const` binding name. They are still valid as
 * *export* names, so a PHP `function delete()` is bound to a safe local and
 * re-exported under its original name. `arguments` and `eval` are not reserved
 * words, but strict mode (which every ES module is in) forbids binding them.
 */
const RESERVED = new Set([
  "arguments", "await", "break", "case", "catch", "class", "const", "continue",
  "debugger", "default", "delete", "do", "else", "enum", "eval", "export",
  "extends", "false", "finally", "for", "function", "if", "implements", "import",
  "in", "instanceof", "interface", "let", "new", "null", "package", "private",
  "protected", "public", "return", "static", "super", "switch", "this", "throw",
  "true", "try", "typeof", "var", "void", "while", "with", "yield",
]);

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Whether a PHP function name can be used directly as a JS binding. */
export function isBindableIdentifier(name: string): boolean {
  return IDENTIFIER.test(name) && !RESERVED.has(name);
}

/**
 * The local binding a name is declared under: the name itself when it is a
 * legal identifier, otherwise a sanitised alias that gets re-exported under
 * the original name. `codegen.ts`, `dts.ts` and the uniqueness guard in
 * `parse.ts` all rely on this one function to agree about aliasing.
 */
export function bindingNameFor(name: string, kind: "function" | "constant"): string {
  if (isBindableIdentifier(name)) return name;
  const prefix = kind === "function" ? "__phpFn" : "__phpConst";
  return `${prefix}_${name.replace(/[^A-Za-z0-9_$]/g, "_")}`;
}

export interface CodegenOptions {
  /** Absolute path of the `.php` file. */
  path: string;
  source: string;
  meta: PhpModuleMeta;
  /** Module specifier (or absolute path) for `bun-php`'s runtime. */
  runtimeSpecifier: string;
  stdout: StdoutMode;
  /** Host directory to mount into the virtual filesystem, if any. */
  root: string | null;
  /** Composer autoloader to require before the module, if any. */
  autoload: string | null;
}

/** Generate the JavaScript module that a `.php` import resolves to. */
export function generateModule(options: CodegenOptions): string {
  const { path, source, meta, runtimeSpecifier, stdout, root, autoload } = options;

  const functions = Object.fromEntries(
    meta.functions.map((fn) => [fn.exportName, fn.phpName]),
  );

  const lines: string[] = [
    `// Generated by bun-php from ${path}`,
    `import { createPhpModule } from ${JSON.stringify(runtimeSpecifier)};`,
    "",
    `const __mod = createPhpModule({`,
    `  id: ${JSON.stringify(path)},`,
    `  source: ${JSON.stringify(source)},`,
    `  functions: ${JSON.stringify(functions)},`,
    `  meta: ${JSON.stringify(meta)},`,
    `  stdout: ${JSON.stringify(stdout)},`,
    `  root: ${JSON.stringify(root)},`,
    `  autoload: ${JSON.stringify(autoload)},`,
    `});`,
    "",
    "export default __mod;",
    "",
  ];

  for (const fn of meta.functions) {
    const name = fn.exportName;
    const call = `(...args) => __mod.call(${JSON.stringify(name)}, args);`;
    if (isBindableIdentifier(name)) {
      lines.push(`export const ${name} = ${call}`);
    } else {
      // Reserved words are legal export names, just not local binding names.
      const alias = bindingNameFor(name, "function");
      lines.push(`const ${alias} = ${call}`);
      lines.push(`export { ${alias} as ${JSON.stringify(name)} };`);
    }
  }

  if (meta.constants.length > 0) lines.push("");
  for (const constant of meta.constants) {
    const value = JSON.stringify(constant.value);
    if (isBindableIdentifier(constant.name)) {
      lines.push(`export const ${constant.name} = ${value};`);
    } else {
      const alias = bindingNameFor(constant.name, "constant");
      lines.push(`const ${alias} = ${value};`);
      lines.push(`export { ${alias} as ${JSON.stringify(constant.name)} };`);
    }
  }

  if (meta.skipped.length > 0) {
    lines.push("");
    lines.push("// Not exported:");
    for (const note of meta.skipped) lines.push(`//   - ${note}`);
  }

  return lines.join("\n") + "\n";
}
