import { bindingNameFor, exportLines, isBindableIdentifier, skippedLines } from "./codegen";
import { parenthesised } from "./php-types";
import type { PhpFunctionMeta, PhpModuleMeta, PhpValue } from "./types";

/**
 * The sidecar `<file>.php.d.ts`. TypeScript resolves `./hello.php` to it the way typed CSS modules
 * work, and it has no imports so it type-checks wherever the `.php` file lives.
 */
export function generateDts(meta: PhpModuleMeta, sourceName: string): string {
  const lines = [
    "// Generated by bun-php. Do not edit.",
    `// Source: ${sourceName}`,
    "",
    "type PhpValue =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | PhpValue[]",
    "  | { [key: string]: PhpValue };",
    "type PhpArray = PhpValue[] | { [key: string]: PhpValue };",
    "",
  ];
  const onDefault: string[] = [];

  for (const fn of meta.functions) {
    const doc = docComment(fn);
    if (doc) lines.push(doc);
    const signature = `(${renderParams(fn)}): Promise<${fn.returnTsType}>`;
    lines.push(
      ...exportLines(fn.exportName, "function", (b) => `declare function ${b}${signature};`),
      "",
    );
    const binding = bindingNameFor(fn.exportName, "function");
    const key = binding === fn.exportName ? binding : JSON.stringify(fn.exportName);
    onDefault.push(`  ${key}: typeof ${binding};`);
  }

  for (const constant of meta.constants) {
    const type = valueType(constant.value);
    lines.push(...exportLines(constant.name, "constant", (b) => `declare const ${b}: ${type};`));
  }
  if (meta.constants.length > 0) lines.push("");

  lines.push(
    "declare const _default: {",
    "  /** Call a PHP function by its fully-qualified name. */",
    "  call(name: string, args: readonly unknown[]): Promise<any>;",
    "  /** Boot the interpreter without calling anything. */",
    "  $ready(): Promise<void>;",
    "  /** Tear down and re-boot, discarding all PHP state. */",
    "  $reset(): Promise<void>;",
    "  /** Shut the interpreter down and drop it from the cache. */",
    "  $dispose(): Promise<void>;",
    "  /** Evaluate arbitrary PHP; this file is already required. */",
    "  $eval(code: string): Promise<any>;",
    "  /** The underlying php-wasm instance. */",
    "  $php(): Promise<any>;",
    '  /** Drain output collected under `stdout: "capture"`. */',
    "  $output(): string;",
    "  /** What the parser found in this file. */",
    "  $meta: {",
    "    functions: readonly unknown[];",
    "    constants: readonly unknown[];",
    "    skipped: readonly string[];",
    "  };",
    ...onDefault,
    "};",
    "export default _default;",
  );

  return [...lines, ...skippedLines(meta)].join("\n") + "\n";
}

function renderParams(fn: PhpFunctionMeta): string {
  const parts: string[] = [];
  // PHP allows a required parameter after an optional one; TypeScript does not, so optionality sticks.
  let optional = false;

  for (const param of fn.params) {
    const name = isBindableIdentifier(param.name) ? param.name : `_${param.name}`;
    if (param.variadic) {
      parts.push(`...${name}: ${parenthesised(param.tsType)}[]`);
      continue;
    }
    optional ||= param.optional;
    parts.push(`${name}${optional ? "?" : ""}: ${param.tsType}`);
  }

  return parts.join(", ");
}

function docComment(fn: PhpFunctionMeta): string | null {
  const notes = fn.doc ? fn.doc.split("\n") : [];

  const byref = fn.params.filter((p) => p.byref).map((p) => `$${p.name}`);
  if (byref.length > 0) {
    if (notes.length > 0) notes.push("");
    notes.push(
      `Note: ${byref.join(", ")} ${byref.length === 1 ? "is" : "are"} by-reference in PHP.`,
      "Arguments cross the boundary by value, so writes are not reflected back.",
    );
  }

  if (notes.length === 0) return null;
  return ["/**", ...notes.map((line) => ` * ${line}`.trimEnd()), " */"].join("\n");
}

/** The literal type of a statically-known constant value. */
function valueType(value: PhpValue): string {
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "number";
  if (typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `readonly [${value.map(valueType).join(", ")}]`;
  const entries = Object.entries(value).map(
    ([key, inner]) => `readonly ${JSON.stringify(key)}: ${valueType(inner)}`,
  );
  return entries.length > 0 ? `{ ${entries.join("; ")} }` : "{}";
}
