import { isBindableIdentifier } from "./codegen";
import type { PhpFunctionMeta, PhpModuleMeta, PhpValue } from "./types";

/**
 * Generate the sidecar `<name>.php.d.ts`.
 *
 * TypeScript resolves `import { greet } from "./hello.php"` to
 * `hello.php.d.ts` by appending extensions to the literal specifier — the same
 * mechanism typed CSS modules rely on. The file is deliberately self-contained
 * (no imports) so it type-checks wherever the `.php` file happens to live.
 */
export function generateDts(meta: PhpModuleMeta, sourceName: string): string {
  const lines: string[] = [
    "// Generated by bun-php. Do not edit.",
    `// Source: ${sourceName}`,
    "",
    "type PhpValue =",
    "  | string",
    "  | number",
    "  | boolean",
    "  | null",
    "  | PhpValue[]",
    "  | { [key: string]: PhpValue };",
    "type PhpArray = PhpValue[] | { [key: string]: PhpValue };",
    "",
  ];

  const exposed: string[] = [];

  for (const fn of meta.functions) {
    const doc = docComment(fn);
    if (doc) lines.push(doc);

    const signature = `(${renderParams(fn)}): Promise<${fn.returnTsType}>`;
    if (isBindableIdentifier(fn.exportName)) {
      lines.push(`export declare function ${fn.exportName}${signature};`);
      exposed.push(`  ${fn.exportName}: typeof ${fn.exportName};`);
    } else {
      const alias = `__phpFn_${fn.exportName.replace(/[^A-Za-z0-9_$]/g, "_")}`;
      lines.push(`declare function ${alias}${signature};`);
      lines.push(`export { ${alias} as ${JSON.stringify(fn.exportName)} };`);
      exposed.push(`  ${JSON.stringify(fn.exportName)}: typeof ${alias};`);
    }
    lines.push("");
  }

  for (const constant of meta.constants) {
    const type = valueType(constant.value);
    if (isBindableIdentifier(constant.name)) {
      lines.push(`export declare const ${constant.name}: ${type};`);
    } else {
      const alias = `__phpConst_${constant.name.replace(/[^A-Za-z0-9_$]/g, "_")}`;
      lines.push(`declare const ${alias}: ${type};`);
      lines.push(`export { ${alias} as ${JSON.stringify(constant.name)} };`);
    }
  }
  if (meta.constants.length > 0) lines.push("");

  lines.push(
    "declare const _default: {",
    "  /** Call a PHP function by its fully-qualified name. */",
    "  call(name: string, args: readonly unknown[]): Promise<any>;",
    "  /** Boot the interpreter without calling anything. */",
    "  $ready(): Promise<void>;",
    "  /** Tear down and re-boot, discarding all PHP state. */",
    "  $reset(): Promise<void>;",
    "  /** Shut the interpreter down and drop it from the cache. */",
    "  $dispose(): Promise<void>;",
    "  /** Evaluate arbitrary PHP; this file is already required. */",
    "  $eval(code: string): Promise<any>;",
    "  /** The underlying php-wasm instance. */",
    "  $php(): Promise<any>;",
    '  /** Drain output collected under `stdout: "capture"`. */',
    "  $output(): string;",
    "  /** What the parser found in this file. */",
    "  $meta: {",
    "    functions: readonly unknown[];",
    "    constants: readonly unknown[];",
    "    skipped: readonly string[];",
    "  };",
    ...exposed,
    "};",
    "export default _default;",
  );

  if (meta.skipped.length > 0) {
    lines.push("");
    lines.push("// Not exported:");
    for (const note of meta.skipped) lines.push(`//   - ${note}`);
  }

  return lines.join("\n") + "\n";
}

function renderParams(fn: PhpFunctionMeta): string {
  const parts: string[] = [];
  // PHP permits a required parameter after an optional one; TypeScript does
  // not, so optionality is made sticky once it starts.
  let optionalFromHere = false;

  for (const param of fn.params) {
    const name = isBindableIdentifier(param.name) ? param.name : `_${param.name}`;

    if (param.variadic) {
      const element = param.tsType.includes(" | ")
        ? `(${param.tsType})`
        : param.tsType;
      parts.push(`...${name}: ${element}[]`);
      continue;
    }

    optionalFromHere ||= param.optional;
    parts.push(`${name}${optionalFromHere ? "?" : ""}: ${param.tsType}`);
  }

  return parts.join(", ");
}

function docComment(fn: PhpFunctionMeta): string | null {
  const notes: string[] = [];
  if (fn.doc) notes.push(...fn.doc.split("\n"));

  const byref = fn.params.filter((p) => p.byref).map((p) => `$${p.name}`);
  if (byref.length > 0) {
    if (notes.length > 0) notes.push("");
    notes.push(
      `Note: ${byref.join(", ")} ${byref.length === 1 ? "is" : "are"} by-reference in PHP.`,
      "Arguments cross the boundary by value, so writes are not reflected back.",
    );
  }

  if (notes.length === 0) return null;
  return ["/**", ...notes.map((line) => ` * ${line}`.trimEnd()), " */"].join("\n");
}

/** Derive a precise literal type from a statically-known constant value. */
function valueType(value: PhpValue): string {
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "number";
  }
  if (typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    return `readonly [${value.map(valueType).join(", ")}]`;
  }
  const entries = Object.entries(value).map(
    ([key, inner]) => `readonly ${JSON.stringify(key)}: ${valueType(inner)}`,
  );
  return entries.length > 0 ? `{ ${entries.join("; ")} }` : "{}";
}
